apiVersion: v1
kind: Service
metadata:
  name: {{ include "cachetest.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cachetest.name" . }}
    helm.sh/chart: {{ include "cachetest.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.db_service.port }}       
      protocol: TCP
      name: postgres
    - name: kube-ping
      targetPort: {{ .Values.kube_ping_service.port }}      
      port: {{ .Values.kube_ping_service.port }}
      protocol: TCP   
  selector:
    app.kubernetes.io/name: {{ include "cachetest.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    cachetest.lb: lb-cachetest
